name: Deploy-backend

on:
  push:
    paths:
      - 'backend/**'

jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}    
        
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      run: |
        docker-compose build mystore_ms
        docker-compose push mystore_ms
        
  deploy:
    name: update deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Set up Python 
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Deploy
        run: | 
          cd backend
          python -m pip install --upgrade pip
          pipenv install -r requirements_deploy.txt
          pipenv run aws configure set region us-east-1 --profile default
          pipenv run aws configure set output json --profile default
          pipenv run aws configure set aws_access_key_id ${{ secrets.ACCES_AMAZON }} --profile default
          pipenv run aws configure set aws_secret_access_key ${{ secrets.SECRET_AMAZON }} --profile default
          pipenv run zappa update
