name: Deploy-frontend

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}    
        
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      run: |
        docker-compose -f pruebasFuncionales.yml build mystore_frontend
        docker-compose -f pruebasFuncionales.yml push mystore_frontend
  test:
    needs: push_to_registry
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0   
      - name: Set up Python 
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: test
        run: | 
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements_func_test.txt
          cd ..
          docker-compose -f pruebasFuncionales.yml up -d
          cd backend
          cd core
          cd func-tests
          python pruebas_funcionales.py
