name: Test python App

on:
  pull_request: 
    branches:
      - master
      - develop-backend
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt 
    - name: testing 
      run: | 
        cd backend
        python3 manage.py test
    - name: Send Slack Notification on Failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: backend
        SLACK_COLOR: "#9e2a2b"
        #SLACK_ICON: https://someurl.com/logo.png
        SLACK_MESSAGE: "backend test failed"
        SLACK_TITLE: Failed execution
        SLACK_USERNAME: Deploy Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
