name: Update-subtrees

on:
  repository_dispatch:
    types: [update-subtrees]

jobs:
  update:
    name: Update Subtrees
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        # Fetch all branches and tags
        fetch-depth: 0

    - name: Configure Git identity
      run: |
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name ${{ secrets.NAME }}
        
    # Actualiza el primer subdirectorio
    - name: Update Backend
      run: git subtree pull --prefix=backend https://github.com/santa51107HD/backend-hotel-nexus.git master

    # Actualiza el segundo subdirectorio
    - name: Update Frontend
      run: git subtree pull --prefix=frontend https://github.com/santa51107HD/frontend-hotel-nexus.git master
    
    # Configura la autenticación de Git
    - name: Set up Git authentication
      run: |
        git config --global credential.helper store
        echo "protocol=https\nhost=github.com\nusername=github-actions[bot]\npassword=${{ secrets.GITHUB_TOKEN }}" > ~/.git-credentials
        
    # Envía los cambios al repositorio en GitHub
    - name: Push changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
